# Generated by Django 4.0.6 on 2022-09-07 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_rename_enable_product_enabled_product_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('total', models.IntegerField()),
                ('discount', models.FloatField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('address', models.CharField(max_length=255)),
                ('vat', models.FloatField(default=0.09)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField()),
                ('ref', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('error', 'Error')], max_length=20)),
                ('authority', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('user_ip', models.CharField(max_length=255)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('price', models.IntegerField()),
                ('discount', models.FloatField()),
                ('name', models.CharField(max_length=255)),
                ('total', models.IntegerField()),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.invoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.product')),
            ],
        ),
    ]
